import { useState } from 'react'
import { ArrowRight, Eye, EyeOff, Leaf, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { api } from './services/api'

const accounts=[['ADMIN','admin@decarbx.com','Admin@123'],['MANAGER','manager@decarbx.com','Manager@123'],['ANALYST','analyst@decarbx.com','Analyst@123'],['PROCUREMENT','procurement@decarbx.com','Procure@123'],['FINANCE','finance@decarbx.com','Finance@123'],['SUPPLIER','supplier@decarbx.com','Supplier@123'],['AUDITOR','auditor@decarbx.com','Auditor@123'],['VIEWER','viewer@decarbx.com','Viewer@123']]

export default function Login({onLogin}){
  const [email,setEmail]=useState(accounts[0][1]),[password,setPassword]=useState(accounts[0][2]),[selected,setSelected]=useState('ADMIN')
  const [show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  const choose=account=>{setSelected(account[0]);setEmail(account[1]);setPassword(account[2]);setError('')}
  const submit=async e=>{e.preventDefault();setLoading(true);setError('');try{onLogin(await api('/auth/login',{method:'POST',body:{email,password}}))}catch(err){setError(err.message)}finally{setLoading(false)}}
  return <div className="login-page">
    <section className="login-story"><div className="login-brand"><span><Leaf/></span>decarb<b>x</b></div><div className="story-copy"><span className="story-kicker">Environmental intelligence</span><h1>Measure what matters.<br/>Change what counts.</h1><p>One trusted workspace for carbon accounting, product footprints, supplier engagement, and climate action.</p><div className="trust-row"><ShieldCheck/><span><strong>Audit-grade data</strong><small>Secure, traceable, assurance-ready</small></span></div></div><div className="orb orb-one"/><div className="orb orb-two"/><footer>Built for a net-zero future.</footer></section>
    <section className="login-form-wrap"><form className="login-form" onSubmit={submit}><div className="mobile-login-brand"><Leaf/> decarb<b>x</b></div><span className="welcome">Welcome back</span><h2>Sign in to DecarbX</h2><p>Access your organization’s environmental workspace.</p><div className="role-picker"><span>Try a role</span><div>{accounts.map(account=><button type="button" className={selected===account[0]?'selected':''} key={account[0]} onClick={()=>choose(account)}>{account[0]}</button>)}</div></div><label>Email address<div className="input-wrap"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></div></label><label>Password<div className="input-wrap"><LockKeyhole/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="form-options"><label><input type="checkbox" defaultChecked/> Remember me</label><button type="button">Forgot password?</button></div>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading}>{loading?'Signing in…':<>Sign in <ArrowRight/></>}</button><div className="demo-note"><strong>{selected} workspace</strong><span>Permissions and data scope are enforced by the API.</span></div></form><p className="login-help">Need access? Contact your organization administrator.</p></section>
  </div>
}
